### ISSUE TITLE
signErrors в ответ приходит всегда 0

### ISSUE THREAD

**Issue by alexssdd** [naffiq/yii2-kkb#5]
На тестовых и боевых сертификатах проверка bank_sign
```
$object->signErrors = $check != 1;
```
Приходит 0, пробовал на нескольких сертификатах, хотя платеж продит нормально.

**Comment by naffiq** [comment]
@alexssdd 

Приветствую и извиняюсь за поздний отклик. Проверю ошибку в ближайшее время и отпишусь.

**Comment by lxShaDoWxl** [comment]
Привет!
ошибка находиться вот тут
https://github.com/naffiq/yii2-kkb/blob/master/KKBPaymentResult.php#L123
первым параметром должно передаваться не cert_id, а весь xml тег bank

**Comment by naffiq** [comment]
@lxShaDoWxl 

Спасибо большое, сейчас исправлю!
Еще бы придумать как тестами покрыть этот кейс :)

**Comment by lxShaDoWxl** [comment]
@naffiq В своё время для меня тут сложно было просто даже локально оттестировать так как надо сравнивать сигнатуру с приватным ключём банка, а что бы создать оригинал то нужен приватный ключ банка, а получить его не возможно так что просто для проверки создавал сигнатуру из приватного ключа клиента и вместо публичного ключа банка использовал публичный ключ клиента.

**Comment by naffiq** [comment]
@lxShaDoWxl 
Взял готовый ответ банка за основу 😀

Помимо того, что я использовал неправильный тег для проверки подписи, я еще и публичный ключ не тот грузил (`kkbca.pem` нужен, а не `test_pub.pem`). Обновил README.

Теперь все работает как надо, тесты исправлены, пользуйтесь на здоровье 💃
