### ISSUE TITLE
Заброшенная библиотека в composer.json

### ISSUE THREAD

**Issue by soulsteel** [naffiq/yii2-kkb#6]
Здравствуйте,  библиотека https://packagist.org/packages/rquadling/lalit больше не поддерживается и ее автор рекомендует https://packagist.org/packages/digitickets/lalit.
Не знаю насколько это критично, но решил вас предупредить об этом.

**Comment by naffiq** [comment]
@soulsteel Спасибо за наводку, постараюсь избавиться от этой зависимости в ближайшее время!

**Comment by naffiq** [comment]
@soulsteel 

Проблема решена, скоро будет новый патч. Спасибо!
